# Generated by Django 3.2.3 on 2021-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0002_auto_20210526_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RemoveField(
            model_name='disciplines',
            name='description',
        ),
        migrations.RemoveField(
            model_name='disciplines',
            name='location',
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(max_length=150, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(max_length=40, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(max_length=150, verbose_name='Школа'),
        ),
    ]
