# Generated by Django 3.2.3 on 2021-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0003_auto_20210526_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplines',
            name='student',
            field=models.ManyToManyField(to='vectorapp.Student'),
        ),
    ]
