# Generated by Django 3.2.3 on 2021-05-27 23:32

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0005_articles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='date_created',
        ),
        migrations.AddField(
            model_name='articles',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
