# Generated by Django 3.2.3 on 2021-05-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0006_auto_20210527_2332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
            ],
        ),
    ]
