# Generated by Django 3.2.3 on 2021-05-30 09:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0007_alter_articles_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
