# Generated by Django 3.2.3 on 2021-05-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0008_alter_student_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
